theme:
  white:
    name: 羊毛白
    background: '#EAEDED'
    text:
      background: '#FFFFFF'
      foreground: '#000000'
      border: '#FFFFFF:1'
    input:
      background: '#FFFFFF'
      foreground: '#000000'
      border: '#000000:1'
  gray:
    name: 深空灰
    background: '#808080'
    text:
      background: '#404040'
      foreground: '#00FF00'
      border: '#000000:1'
    input:
      background: '#404040'
      foreground: '#00FF00'
      border: '#000000:2'
